# Generated by Django 5.2.16 on 2026-07-26 19:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Symbol / نماد')),
                ('side', models.CharField(choices=[('buy', 'Buy / خرید'), ('sell', 'Sell / فروش')], max_length=4, verbose_name='Side / جهت')),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Entry Price / قیمت ورود')),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Exit Price / قیمت خروج')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantity / تعداد')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date / تاریخ')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes / یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade / معامله',
                'verbose_name_plural': 'Trades / معاملات',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
